# Generated by Django 5.0.7 on 2024-08-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_orderfield_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='models',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
