# Generated by Django 5.0.7 on 2024-08-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='models',
            new_name='image',
        ),
    ]
