# Generated by Django 5.0.7 on 2024-08-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_models_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='county',
        ),
    ]
